### PR TITLE
Waveform demo for riscv-mini , rocket16 and  VCD header comparison (module and signal)

### PR DESCRIPTION
**Pull request by MSPDUTTA**

### CODE REVIEW

**Comment by sbeamer** [comment]
Thank you for making this! Can you revise the following:

1. Refactor the pull request into two pull requests? One for `waveform-demo` and one for `waveform-test`
2. Soft link`TestHarness.DefaultConfig.1609.fir` instead of copying it.
3. Do not include `libfesvr.so` (a binary compiled for the host platform). I doubt it is needed in that exact location, and can probably change the paths in the Makefile to use the appropriate fesvr components from rocket16. If you do need it in that location, please use a soft link.

**Comment by MSPDUTTA** [comment]
I have sent a request only for the waveform-demo with all these suggested updates.

**Comment by sbeamer** [comment]
I did a clean pull and after some modification, go it to run!

Please fix the following so others can just do a clean pull:

1. For `waveform-demo/rocket16`, please fix the Makefile and such with regards to `libfesvr.so`. The easiest might be too soft link the riscv directory from rocket16.
2. Bump the essent submodule pointer to include the VCD/FST commits.
3. Softlink `Tile.fir` for riscv-mini.

**Comment by MSPDUTTA** [comment]
I have updated with these modifications!

**Comment by sbeamer** [comment]
Thank you!

**Pull request merged**
